### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Fale** [gregturn/asciidoctor-packt#22]
Hi,
Thanks a lot for this tool :).
I've noticed that the titles do not appear as "Heading 1,Heading 1 [PACKT]" but as "Heading 1". Is this because Packt has "copied" standard headings or it this a bug?

Thanks again for creating a sharing this awesome tool :), you made my day.

**Comment by Fale** [comment]
Hi,
sorry for the delay.

I've used this adoc file: https://fale.fedorapeople.org/asciidoctor/test.adoc
I've executed: `asciidoctor -T slim -b packt test.adoc`
And I've received this fodt file: https://fale.fedorapeople.org/asciidoctor/test.fodt

I now see two problems:

* Margins are too small
* The chapter number is in the second line instead of i nthe first one (the first line is empthy)

Thanks a lot :)

**Comment by gregturn** [comment]
@Fale I realize that I haven't spent any time on processing your comments. Things are busy. What I'm hoping is that you have been able to make tweaks on your local clone of this project to at least keep going forward with writing your title using asciidoctor. I sounds like a good success story that I think deserves more tweeting. Definitely cc @mojavelinux in your twitter stream to increase the visibility. Who knows? Perhaps one day, Packt may support asciidoctor natively!

**Comment by Fale** [comment]
Hi @gregturn.
I'm able to do the majority of things. The process is not perfect, but the result is compliant with the policies.
I've not thought about tweeting... you know, I have one tweet since Aug 24 XD. I'll do it ;).
